# Generated by Django 3.1.7 on 2021-03-19 03:50

import angalabiri.users.models
import angalabiri.users.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='accept_cookies',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='accept_terms',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='accessed_with',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='System IP Accessed with'),
        ),
        migrations.AddField(
            model_name='user',
            name='bvn',
            field=models.CharField(max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_input, only 11 fields', message='Invalid BVN', regex='^[0-9]*$')], verbose_name='Bank Verification Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(code='invalid_input, only strings', message='First Name must be Alphabetic', regex='^[a-zA-Z]*$')], verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Gender'), ('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('Not Known', 'Not Known')], max_length=9, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Current IP Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(code='invalid_input, only strings', message='Last Name must be Alphabetic', regex='^[a-zA-Z]*$')], verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='lga',
            field=models.CharField(blank=True, choices=[('', 'LGA'), ('Brass', 'Brass'), ('Ekeremor', 'Ekeremor'), ('Kolokuma Opokuma', 'Kolokuma Opokuma'), ('Nembe', 'Nembe'), ('Ogbia', 'Ogbia'), ('Sagbama', 'Sagbama'), ('Southern Ijaw', 'Southern Ijaw'), ('Yenagoa', 'Yenagoa')], max_length=16, null=True, verbose_name='Local Government Area'),
        ),
        migrations.AddField(
            model_name='user',
            name='mid_name',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(code='invalid_input, only strings', message='Middle Name must be Alphabetic', regex='^[a-zA-Z]*$')], verbose_name='Middle Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='own_shop',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Format: +234xxxxxxxxxx', max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_input, only 14 fields including +234xxxxxxxxxx', message='Invalid Number', regex='/^+234[0-9]{11}/')], verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.FileField(blank=True, help_text='supported formats: [jpeg/png/svg]', null=True, upload_to=angalabiri.users.models.citizen_image, validators=[angalabiri.users.validators.validate_user_photo_extension], verbose_name='Profile Photo'),
        ),
        migrations.AddField(
            model_name='user',
            name='royals',
            field=models.CharField(blank=True, choices=[('', 'Royal Status'), ('Queen', 'Queen'), ('King', 'King'), ('Chief', 'Chief'), ('Prince', 'Prince'), ('Princess', 'Princess')], max_length=12, null=True, verbose_name='Royal Status'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Community Status'), ('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Mss', 'Mss'), ('Dr', 'Dr'), ('Engr', 'Engr'), ('Sir', 'Sir'), ('Madam', 'Madam')], max_length=8, null=True, verbose_name='Community Status'),
        ),
    ]
