# Generated by Django 3.1.7 on 2021-03-19 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210319_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Prefix'), ('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Mss', 'Mss'), ('Dr', 'Dr'), ('Engr', 'Engr'), ('Sir', 'Sir'), ('Madam', 'Madam')], max_length=8, null=True, verbose_name='Prefix'),
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('Old', 'Old'), ('Current', 'Current')], default='Old', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('flat', models.CharField(blank=True, max_length=222, null=True, verbose_name='Flat')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Addresse',
                'verbose_name_plural': 'User Addresses',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
    ]
