# Generated by Django 3.1.7 on 2021-03-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_stock',
            field=models.BooleanField(default=False),
        ),
    ]
