# Generated by Django 3.1.7 on 2021-03-31 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_old_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='varation_type',
            field=models.CharField(blank=True, choices=[('SIZE', 'SIZE'), ('WEIGHT', 'WEIGHT'), ('COLOR', 'COLOR')], default='SIZE', max_length=150, null=True, verbose_name='Type of Variation to add'),
        ),
    ]
