# Generated by Django 3.1.7 on 2021-03-31 23:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productvariation_varation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='varation_type',
        ),
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Product Color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'verbose_name': 'Product Color',
                'verbose_name_plural': 'Product Colors',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
    ]
