# Generated by Django 3.1.7 on 2021-04-06 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210406_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='card',
            name='billing_profile',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='billing_profile',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='BillingProfile',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Charge',
        ),
    ]
