# Generated by Django 3.1.7 on 2021-03-22 01:02

import angalabiri.causes.models
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0002_auto_20190103_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Cause Title')),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=angalabiri.causes.models.cause_file_path, verbose_name='Upload Image')),
                ('pub_date', models.DateField(null=True, verbose_name='Post Published Date')),
                ('end_date', models.DateField(null=True, verbose_name='Post Published Date')),
                ('tt_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('donate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('draft', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('added_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='added_by')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(help_text='Categorize this item.', to='category.Category')),
                ('tags', models.ManyToManyField(help_text='Tag this item.', to='category.Tag')),
            ],
            options={
                'verbose_name': 'Cause',
                'verbose_name_plural': 'Causes',
                'ordering': ['title', '-end_date'],
                'managed': True,
            },
        ),
    ]
