# Generated by Django 3.1.7 on 2021-03-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='max_donation',
            field=models.DecimalField(blank=True, decimal_places=2, default=100000.0, max_digits=20, null=True),
        ),
    ]
