# Generated by Django 3.1.7 on 2021-03-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0002_cause_max_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='end_date',
            field=models.DateField(null=True, verbose_name='End Published Date'),
        ),
    ]
