# Generated by Django 3.1.7 on 2021-03-28 19:57

import angalabiri.causes.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0003_auto_20210324_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, size=[1920, 1148], upload_to=angalabiri.causes.models.cause_file_path, verbose_name='Upload Cause Image'),
        ),
    ]
