# Generated by Django 3.1.7 on 2021-03-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='added_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='added_by'),
        ),
    ]
