# Generated by Django 3.1.7 on 2021-03-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210327_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='added_by',
            field=models.CharField(blank=True, max_length=555, null=True, verbose_name='added_by'),
        ),
    ]
