# Generated by Django 3.1.7 on 2021-03-28 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210328_0422'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
