# Generated by Django 3.1.7 on 2021-03-28 08:44

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Post Title')),
                ('email', models.EmailField(max_length=255, null=True, verbose_name='Your Email')),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True, unique=True)),
                ('pub_date', models.DateField(null=True, verbose_name='Suggestion Published Date')),
                ('draft', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Suggestion',
                'verbose_name_plural': 'Suggestions',
                'ordering': ['title', '-pub_date'],
                'managed': True,
            },
        ),
    ]
